function getSeedImages() {
  return [
    "https://avataaars.io/?accessoriesType=Round&avatarStyle=Circle&clotheColor=PastelOrange&clotheType=Overall&eyeType=Side&eyebrowType=FlatNatural&facialHairColor=Blonde&facialHairType=Blank&graphicType=Skull&hairColor=Blonde&hatColor=PastelBlue&mouthType=Eating&skinColor=Brown&topType=LongHairNotTooLong",
    "https://avataaars.io/?accessoriesType=Round&avatarStyle=Circle&clotheColor=PastelRed&clotheType=BlazerSweater&eyeType=Close&eyebrowType=RaisedExcited&facialHairColor=Black&facialHairType=MoustacheFancy&graphicType=Hola&hairColor=Platinum&hatColor=PastelBlue&mouthType=Serious&skinColor=Light&topType=WinterHat4",
    "https://avataaars.io/?accessoriesType=Prescription01&avatarStyle=Circle&clotheColor=PastelYellow&clotheType=GraphicShirt&eyeType=EyeRoll&eyebrowType=SadConcerned&facialHairColor=BlondeGolden&facialHairType=BeardMagestic&graphicType=SkullOutline&hairColor=PastelPink&hatColor=Pink&mouthType=Twinkle&skinColor=Pale&topType=LongHairStraight",
    "https://avataaars.io/?avatarStyle=Circle&topType=LongHairStraight&accessoriesType=Blank&hairColor=BrownDark&facialHairType=Blank&clotheType=BlazerShirt&eyeType=Default&eyebrowType=Default&mouthType=Default&skinColor=Light",
    "https://avataaars.io/?accessoriesType=Round&avatarStyle=Circle&clotheColor=Blue02&clotheType=Hoodie&eyeType=Dizzy&eyebrowType=AngryNatural&facialHairType=BeardLight&hairColor=Auburn&mouthType=Serious&skinColor=Light&topType=WinterHat2",
    "https://avataaars.io/?accessoriesType=Wayfarers&avatarStyle=Circle&clotheColor=Blue03&clotheType=Overall&eyeType=Wink&eyebrowType=Default&facialHairColor=BlondeGolden&facialHairType=Blank&hairColor=Auburn&hatColor=Red&mouthType=Tongue&skinColor=Black&topType=LongHairFrida",
    "https://avataaars.io/?accessoriesType=Blank&avatarStyle=Circle&clotheColor=Gray01&clotheType=ShirtVNeck&eyeType=WinkWacky&eyebrowType=UpDownNatural&facialHairColor=Blonde&facialHairType=BeardLight&hairColor=SilverGray&hatColor=PastelRed&mouthType=Tongue&skinColor=DarkBrown&topType=Hijab",
    "https://avataaars.io/?accessoriesType=Prescription01&avatarStyle=Circle&clotheColor=Gray01&clotheType=CollarSweater&eyeType=Hearts&eyebrowType=RaisedExcitedNatural&facialHairColor=Red&facialHairType=Blank&hairColor=Platinum&hatColor=Gray01&mouthType=Twinkle&skinColor=DarkBrown&topType=LongHairFroBand",
    "https://avataaars.io/?accessoriesType=Wayfarers&avatarStyle=Circle&clotheColor=Blue01&clotheType=BlazerSweater&eyeType=Default&eyebrowType=FlatNatural&facialHairColor=BrownDark&facialHairType=MoustacheMagnum&hairColor=Auburn&hatColor=PastelBlue&mouthType=Sad&skinColor=DarkBrown&topType=Turban",
    "https://avataaars.io/?accessoriesType=Blank&avatarStyle=Circle&clotheColor=PastelRed&clotheType=CollarSweater&eyeType=Squint&eyebrowType=SadConcernedNatural&facialHairColor=Red&facialHairType=BeardMagestic&hairColor=BlondeGolden&hatColor=PastelGreen&mouthType=Twinkle&skinColor=DarkBrown&topType=LongHairDreads",
    "https://avataaars.io/?accessoriesType=Blank&avatarStyle=Circle&clotheColor=Blue01&clotheType=BlazerSweater&eyeType=Dizzy&eyebrowType=Angry&facialHairColor=BrownDark&facialHairType=Blank&hairColor=Auburn&hatColor=Gray02&mouthType=Twinkle&skinColor=DarkBrown&topType=ShortHairDreads01",
    "https://avataaars.io/?accessoriesType=Wayfarers&avatarStyle=Circle&clotheColor=Pink&clotheType=BlazerShirt&eyeType=Hearts&eyebrowType=AngryNatural&facialHairColor=Blonde&facialHairType=MoustacheMagnum&hairColor=BrownDark&hatColor=Gray02&mouthType=Sad&skinColor=Yellow&topType=LongHairStraight2",
    "https://avataaars.io/?accessoriesType=Kurt&avatarStyle=Circle&clotheColor=PastelGreen&clotheType=ShirtVNeck&eyeType=Default&eyebrowType=UnibrowNatural&facialHairColor=BrownDark&facialHairType=BeardLight&hairColor=Black&hatColor=PastelGreen&mouthType=ScreamOpen&skinColor=Yellow&topType=WinterHat2",
    "https://avataaars.io/?accessoriesType=Wayfarers&avatarStyle=Circle&clotheColor=Gray02&clotheType=ShirtScoopNeck&eyeType=Wink&eyebrowType=RaisedExcited&facialHairColor=Blonde&facialHairType=BeardMedium&hairColor=Black&hatColor=Gray01&mouthType=Grimace&skinColor=Yellow&topType=LongHairFro",
    "https://avataaars.io/?accessoriesType=Prescription02&avatarStyle=Circle&clotheColor=PastelBlue&clotheType=BlazerSweater&eyeType=Surprised&eyebrowType=FlatNatural&facialHairColor=BrownDark&facialHairType=MoustacheFancy&hairColor=Blonde&hatColor=PastelBlue&mouthType=Default&skinColor=Black&topType=Hijab",
    "https://avataaars.io/?accessoriesType=Prescription02&avatarStyle=Circle&clotheColor=Blue03&clotheType=Hoodie&eyeType=Surprised&eyebrowType=UpDownNatural&facialHairColor=Blonde&facialHairType=Blank&hairColor=BrownDark&hatColor=Gray01&mouthType=Twinkle&skinColor=Tanned&topType=WinterHat3",
    "https://avataaars.io/?accessoriesType=Prescription02&avatarStyle=Circle&clotheColor=PastelOrange&clotheType=ShirtCrewNeck&eyeType=Close&eyebrowType=UnibrowNatural&facialHairColor=BrownDark&facialHairType=Blank&hairColor=Black&hatColor=Blue03&mouthType=Twinkle&skinColor=Light&topType=NoHair",
    "https://avataaars.io/?accessoriesType=Round&avatarStyle=Circle&clotheColor=White&clotheType=ShirtCrewNeck&eyeType=WinkWacky&eyebrowType=Default&facialHairColor=Red&facialHairType=Blank&graphicType=Hola&hairColor=BrownDark&hatColor=PastelRed&mouthType=Concerned&skinColor=Pale&topType=WinterHat3",
    "https://avataaars.io/?accessoriesType=Sunglasses&avatarStyle=Circle&clotheColor=Blue02&clotheType=BlazerSweater&eyeType=Default&eyebrowType=UpDownNatural&facialHairColor=Black&facialHairType=BeardMedium&graphicType=Diamond&hairColor=SilverGray&hatColor=PastelOrange&mouthType=Eating&skinColor=Pale&topType=LongHairFrida",
    "https://avataaars.io/?accessoriesType=Blank&avatarStyle=Circle&clotheColor=Blue01&clotheType=CollarSweater&eyeType=EyeRoll&eyebrowType=UnibrowNatural&facialHairColor=BrownDark&facialHairType=BeardMagestic&graphicType=Bat&hairColor=BrownDark&hatColor=Blue02&mouthType=Eating&skinColor=Brown&topType=Eyepatch",
    "https://avataaars.io/?accessoriesType=Prescription01&avatarStyle=Circle&clotheColor=Red&clotheType=CollarSweater&eyeType=Hearts&eyebrowType=Default&facialHairColor=Red&facialHairType=BeardMedium&graphicType=Bat&hairColor=PastelPink&hatColor=PastelRed&mouthType=Tongue&skinColor=DarkBrown&topType=LongHairStraight",
    "https://avataaars.io/?accessoriesType=Round&avatarStyle=Circle&clotheColor=Gray01&clotheType=BlazerSweater&eyeType=Happy&eyebrowType=SadConcernedNatural&facialHairColor=BlondeGolden&facialHairType=BeardMagestic&graphicType=Hola&hairColor=BrownDark&hatColor=Blue01&mouthType=Tongue&skinColor=Pale&topType=ShortHairShortCurly",
    "https://avataaars.io/?accessoriesType=Blank&avatarStyle=Circle&clotheColor=PastelYellow&clotheType=ShirtScoopNeck&eyeType=EyeRoll&eyebrowType=UpDownNatural&facialHairColor=Black&facialHairType=BeardLight&graphicType=Skull&hairColor=Auburn&hatColor=PastelRed&mouthType=Tongue&skinColor=DarkBrown&topType=WinterHat4",
    "https://avataaars.io/?accessoriesType=Prescription02&avatarStyle=Circle&clotheColor=Blue02&clotheType=CollarSweater&eyeType=WinkWacky&eyebrowType=DefaultNatural&facialHairColor=Auburn&facialHairType=BeardLight&graphicType=Skull&hairColor=BlondeGolden&hatColor=Black&mouthType=ScreamOpen&skinColor=Black&topType=ShortHairDreads01",
    "https://avataaars.io/?accessoriesType=Kurt&avatarStyle=Circle&clotheColor=PastelOrange&clotheType=ShirtCrewNeck&eyeType=Side&eyebrowType=Angry&facialHairColor=Brown&facialHairType=MoustacheFancy&graphicType=Selena&hairColor=BrownDark&hatColor=PastelOrange&mouthType=Smile&skinColor=Light&topType=Turban",
  ];
}

module.exports = { getSeedImages };
